config/routes.rb
Keepin::Application.routes.draw do
  match "/login",  :to => "user_sessions#new"
  match "/logout", :to => "user_sessions#destroy"
  match "/signup", :to => "users#new"
  match '/addons',  :to => 'pages#addons'
  match '/mobile',  :to => 'pages#mobile'
  match '/plugins', :to => 'pages#plugins'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/get_word_tags', :to => 'words#get_word_tags'
  
  match 'users/:id/words/:word', :to => 'words#show_word', :as => "show_word"
  
  match 'users/:id/tag/:name', :to => 'users#show_word_by_tag', :as => "show_tag_word"

  root :to => 'pages#home'
  
  get "users/new"

  get "sessions/new"

  resources :users do
    resources :words
  end
  
  resources :user_sessions
  
  post "words/add_tag"  
  
  post "words/delete_tag"
  
  post "sessions/userid"

  post "words/update_tag"
  
  post "words/update_words"

end

app/views/pages/addons.html.erb
<div class="download-container">
  <div class="chosen_addon" id="firefox-plugin">
    <%= render 'layouts/firefox-plugin-download' %>
  </div>
  <div class="chosen_addon" id="android" style="display: none">
    <%= render 'layouts/android-download' %>
  </div>
  <div class="select">
    <h3>Choose Addon:</h3>
    <ul>
      <li class="firefox">
        <div>
          <img src="/stylesheets/img/firefox-plugin.png">
          <a>firefox plugin</a>
        </div>
      </li>
      <li class="android">
        <div>
          <img src="/stylesheets/img/android.png">
          <a>Android</a>
        </div>
      </li>
    </ul>
  </div>
  <div class="other">
  </div>
</div>

<script type="text/javascript">
    $(function() {
        $('li.firefox').live("click", function() {
            if ($("div#firefox-plugin").css("display") == "none") {
                $("div#android").fadeOut("slow", function() {
                    $("div#firefox-plugin").fadeIn("slow")
                })
            }
        })
        $('li.android').live("click", function() {
            if ($("div#android").css("display") == "none") {
                $("div#firefox-plugin").fadeOut("slow", function() {
                    $("div#android").fadeIn("slow")
                })
            }
        })
    })
</script>

app/views/pages/home.html.erb
<div>
  <div id="left-panel">
    <div id="info-panel">
      <h1>Start learning</h1>

      <div class="subtag">
        <span>Start today to put yourself into different learning experience:<br/> Smart facilitating/Efficient/Fun</span>
      </div>
    </div>
    <div id="chart-panel">
      <div id="chart-wrapper">
        <div id="chart">
          <div id="bars">
            <div class="bar first">
              <div class="pointer"></div>
              <div class="description">
                <p>
                  Capture<br>
                  <%= image_tag("plugin.png", :width=>'48', :height=>'48') %>
                  <%= image_tag("safari.png", :width=>'48', :height=>'48') %>
                </p>
              </div>
            </div>
            <div class="bar second">
              <div class="pointer"></div>
              <div class="description">
                <p>
                  <%= image_tag("iphone.png", :width=>'48', :height=>'48') %>
                  <%= image_tag("android.png", :width=>'48', :height=>'48') %><br>
                  Sync
                </p>
              </div>
            </div>
            <div class="bar third">
              <div class="pointer"></div>
              <div class="description">
                <p>
                  Learn<br>
                  <%= image_tag("train.png", :width=>'48', :height=>'48') %> <%= image_tag("bus.png", :width=>'48', :height=>'48') %>
                  <br>

                </p>
              </div>
            </div>
            <div class="bar fourth">
              <div class="pointer"></div>
              <div class="description">
                <p>
                  <%= image_tag("bar_chart.png", :width=>'48', :height=>'48') %> <%= image_tag("line_chart.png", :width=>'48', :height=>'48') %>
                  Track<br>
                </p>
              </div>
            </div>
            <div class="bar fifth">
              <div class="pointer"></div>
              <div class="description">
                <p>
                  Share<br>
                  <%= image_tag("community.png", :width=>'48', :height=>'48') %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div id="right-panel">
    <link rel=StyleSheet href="/stylesheets/home_sign_in.css" type="text/css" media=screen>
		<%= form_for(@user) do |f| %>
		  <% if @user.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

		      <ul>
		      <% @user.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

		  <div class="field">
		    <%= f.label :username %><br />
		    <%= f.text_field :username %>
		  </div>
		  <div class="field">
		    <%= f.label :email %><br />
		    <%= f.text_field :email %>
		  </div>
		  <div class="field">
		    <%= f.label :password %><br />
		    <%= f.password_field :password %>
		  </div>
		  <div class="field">
		      <%= f.label :password_confirmation %><br />
		      <%= f.password_field :password_confirmation %>
		    </div>
		  <div class="actions">
		    <%= f.submit %>
		  </div>
		<% end %>
    </div>


  </div>
</div>

app/views/pages/home_bak.html.erb
<div>
	<div id="left-panel">
		<div id="info-panel">
			<h1>Start learning</h1>
			<div class="subtag">
			<span>Start today to put yourself into different learning experience:<br /> Smart facilitating/Efficient/Fun</span>
			</div>
		</div>
		<div id="chart-panel">
			<div id="chart-wrapper">
				<div id="chart">
					<div id="bars">
						<div class="bar first">
							<div class="pointer"></div>
							<div class="description">
								<p>
									Capture<br>
									<%= image_tag("plugin.png", :width=>'48', :height=>'48') %>
									<%= image_tag("safari.png",  :width=>'48', :height=>'48') %>
								</p>
							</div>
						</div>
						<div class="bar second">
							<div class="pointer"></div>
							<div class="description">
								<p>
									<%= image_tag("iphone.png", :width=>'48', :height=>'48') %>
									<%= image_tag("android.png",  :width=>'48', :height=>'48') %><br>
									Sync
								</p>
							</div>
						</div>
						<div class="bar third">
							<div class="pointer"></div>
							<div class="description">
								<p>
									Learn<br>
									<%= image_tag("train.png", :width=>'48', :height=>'48') %> <%= image_tag("bus.png",  :width=>'48', :height=>'48') %><br>

								</p>
							</div>
						</div>
						<div class="bar fourth">
							<div class="pointer"></div>
							<div class="description">
								<p>
									<%= image_tag("bar_chart.png", :width=>'48', :height=>'48') %> <%= image_tag("line_chart.png",  :width=>'48', :height=>'48') %>
									Track<br>
								</p>
							</div>
						</div>
						<div class="bar fifth">
							<div class="pointer"></div>
							<div class="description">
								<p>
									Share<br>
									<%= image_tag("community.png", :width=>'48', :height=>'48') %>
								</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="right-panel">
		<link rel=StyleSheet href="stylesheets/home_sign_in.css" type="text/css" media=screen>
		<div id="sign-in">
			<h2>Start Study? </h2>
			<div class="sign-in-info">Sign in with your Email and Password.
			</div>
			<%= form_for(:session, :url => sessions_path ) do |f| %>

			<div class="field">
			  <%= f.label :email %>
			  <%= f.text_field :email , :autocomplete => :off %>
			<div class="pointer"></div>
			</div>

			<div class="field">
			  <%= f.label :password %>
			  <%= f.password_field :password ,:autocomplete => :off %>
			<div class="pointer"></div>
			</div>

			<div class="action">
			  <%= f.submit "Sign in" ,:autocomplete => :off%>
			</div>
			<% end %>

			<p>New user? <%= link_to "Sign up!", signup_path %></p>

		  <% if !@user.nil? %>
		  <% end %>
		</div>
	</div>
</div>