config/routes.rb
Keepin::Application.routes.draw do
  match "/login",  :to => "user_sessions#new"
  match "/logout", :to => "user_sessions#destroy"
  match "/signup", :to => "users#new"
  match '/addons',  :to => 'pages#addons'
  match '/mobile',  :to => 'pages#mobile'
  match '/plugins', :to => 'pages#plugins'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/get_word_tags', :to => 'words#get_word_tags'
  
  match 'users/:id/words/:word', :to => 'words#show_word', :as => "show_word"
  
  match 'users/:id/tag/:name', :to => 'users#show_word_by_tag', :as => "show_tag_word"

  root :to => 'pages#home'
  
  get "users/new"

  get "sessions/new"

  resources :users do
    resources :words
  end
  
  resources :user_sessions
  
  post "words/add_tag"  
  
  post "words/delete_tag"
  
  post "sessions/userid"

  post "words/update_tag"
  
  post "words/update_words"

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
      new_record? ? nil : [ self.send(self.class.primary_key) ]
   end

   def persisted?
     false
   end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to root_url
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    redirect_to root_url
  end
end

app/views/user_sessions/new.html.erb
<content>

  <h2>Sign in</h2>

  <%= form_for(:user_session, :url => user_sessions_path) do |f| %>

      <div class="field">
        <%= f.label :email %>
        <br/>
        <%= f.text_field :email %>
      </div>

      <div class="field">
        <%= f.label :password %>
        <br/>
        <%= f.password_field :password %>
      </div>

      <div class="action">
        <%= f.submit "Sign in"%>
      </div>
  <% end %>

  <p>New user? <%= link_to "Sign up!", signup_path %></p>

</content>