config/routes.rb
Keepin::Application.routes.draw do
  match "/login",  :to => "user_sessions#new"
  match "/logout", :to => "user_sessions#destroy"
  match "/signup", :to => "users#new"
  match '/addons',  :to => 'pages#addons'
  match '/mobile',  :to => 'pages#mobile'
  match '/plugins', :to => 'pages#plugins'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/get_word_tags', :to => 'words#get_word_tags'
  
  match 'users/:id/words/:word', :to => 'words#show_word', :as => "show_word"
  
  match 'users/:id/tag/:name', :to => 'users#show_word_by_tag', :as => "show_tag_word"

  root :to => 'pages#home'
  
  get "users/new"

  get "sessions/new"

  resources :users do
    resources :words
  end
  
  resources :user_sessions
  
  post "words/add_tag"  
  
  post "words/delete_tag"
  
  post "sessions/userid"

  post "words/update_tag"
  
  post "words/update_words"

end

app/views/layouts/_android-download.html.erb
<div class="actions">
  <div class="app-header">
    <h2>WoJiDe for Android</h2>

    <p class="compatibility">Compatible with devices running Android 2.1 or later.</p>
  </div>
  <button class="download-button" id="android">Download Now</button>
</div>
<div class="android-img">
  <img src=/stylesheets/img/android-flashcard.png style="margin-right: -36px;">
  <img src=/stylesheets/img/android-signin.png>
</div>

<script type="text/javascript">
  $(function(){
      $("button#android").live('click',function(){
          window.location.href = '/plugins/AndroidKeepin.apk';
      })
  })
</script>

app/views/layouts/_cards.html.erb
<div id="cards">
  <div class="new-sponsorListHolder">
    <% @words.reverse %>
        <% @words.each { |word| %>

        <div id='<%= word.word %>' class='one-word-div'>

          <div class="sponsor" title="Click to flip">

            <div class="sponsorFlip box-shadow" word_id='<%= word.id %>'>
              <ul class="star-ul">
                <li>
                  <% if (word.tags.find_by_name("starred") != nil) %>
                      <div class="starred" title="Click to mark Unstarred"></div>
                  <% else %>
                      <div class="unstarred" title="Click to mark Starred"></div>
                  <% end %>
                </li>
              </ul>

              <div style="padding: 10px 10px 40px">
                <%= time_ago_in_words(word.updated_at) %>
                <div class='word-content'>
                  <%= word.word %>
                </div>
              </div>
            </div>

            <div class="sponsorData">
              <div class="sponsorDescription">
                <div style="font-size:30px;text-align:center;margin-top:20px"><%= word.translation %></div>
              </div>
              <div class="sponsorURL">
                <a href="<%= word.link %>"><%= (word.sample || word.link) %></a>
              </div>
            </div>


          </div>

        </div>

    <% } %>

  </div>
</div>

app/views/layouts/_firefox-plugin-download.html.erb
<div class="actions">
  <div class="app-header">
    <h2>WoJiDe Firefox Plugin</h2>

    <p class="compatibility">make it easy to add words to WoJiDe</p>
  </div>
  <button class="download-button" id="firefox">Download Now</button>
</div>
<div class="android-img">
  <img src=/stylesheets/img/firefox-shot-modified.png>
</div>

<script type="text/javascript">
    $(function() {
        if ($.browser.mozilla) {
            $("button#firefox").text("Add to Firefox");
        }

        $("button#firefox").live('click', function() {
            if ($.browser.mozilla) {
                var params = {
                    "Keepin": { URL: "/plugins/wojide.xpi",
                        toString: function () {
                            return this.URL;
                        }
                    }
                };
                InstallTrigger.install(params);
                return false;
            } else {
                window.location.href = "/plugins/wojide.xpi";
            }
        })

    })
</script>

app/views/layouts/_footer.html.erb
<div id="footer">
    <div class="container_16">
			<div class="grid_12 prefix_2">
	<div class="grid_6 alpha omega">
	© Copyright 2010 KeepIn
	</div>
	<!-- end .grid_6 -->
	<div class="grid_6">
			<ul id="footernav">
			<li><a href="../">About KeepIn</a></li>
			<li><a href="../services">Our Services</a></li>
			<li><a href="../portfolio">Portfolio</a></li>
		   	<li class="last"><a href="../contact">Contact</a></li>
			</ul>
			</div></div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div id="header" style="background-color:#333333">
  <h5 id="main-logo">
New Words For Me
  </h5>
  <ul id="nav">
	  <%unless (current_user)%>
		  <%= form_for(:user_session, :url => user_sessions_path) do |f| %>
		      <div class="field">
		        <%= f.label :email %>
		        <%= f.text_field :email %>
		      </div>
		      <div class="field">
		        <%= f.label :password %>
		        <%= f.password_field :password %>
		      </div>
		      <div class="field action">
				<label>&nbsp;&nbsp;&nbsp;</label>
		        <%= f.submit "Sign in"%>
		      </div>
		  <% end %>
	  <% end %>
	  <%if (current_user)%>
		<%= tabs_tag do |tab| %>
	 	  <%= tab.home      'Logout', logout_path %>
		  <%= tab.addons    'AddOns', addons_path %>
	 	  <%= tab.home      'Home', user_path(current_user) %>
		<% end %>
	  <% end %>
  </ul>
  <div style="clear:both"></div>
</div>

app/views/layouts/_keep-in-mind-box.html.erb
<div class="main-tweet-box">
	<div class="tweet-box">
		<div class="tweet-box-title">
			<h2>
				Do you learn something new?
			</h2>
		</div>
		<div class="text-area">
			<div class="text-area-editor twttr-editor">
				<%= form_for([ @user, Word.new ]) do |f| %>
				  <div class="field">
				    <%= f.text_area :word, :class=> "twitter-anywhere-tweet-box-editor", :style=>"width: 482px; height: 56px;" %>
				  </div>
				<div class="tweet-button-container">
					<span >	try this formate apple@i love apple <b>or</b> apple@http://google.com </span>
					<%= f.submit "Keep In Mind" %>
					<!-- <img style="display: none;" class="tweet-spinner" src="/images/spinner.gif">
						<a class="tweet-button button disabled" href="#">Keep In Mind</a> -->
				</div>
				<% end %>
				<ul class="autocomplete-container"
					style="width: 498px; top: 73px; left: 0px; visibility: hidden;"></ul>
			</div>
		</div>
	</div>
    <%= render 'layouts/tags_list' %>
</div>

app/views/layouts/_signin-signup.html.erb
<%= stylesheet_link_tag 'signin-signup', :media => 'screen' %>

app/views/layouts/_slider.html.erb
<div id="featured-box">

  <div class="orbit-wrapper" id="slides">
    <div class="slides_container">
      <div class="slide">
        <div class="word" id='word1'>2</div>
        <div class="slide_back">2</div>
      </div>
      <div class="slide">
        <div class="word" id='word2'>3</div>
        <div class="slide_back">3</div>
      </div>
    </div>
    <!--<div class="timer">-->
      <!--<span class="mask move">-->
        <!--<span class="rotator move" style="-moz-transform: rotate(294deg);">-->
        <!--</span></span><span class="pause">-->
      <!--</span>-->
    <!--</div>-->
    <div class="slider-nav">
      <span class="next">Right</span>
      <span class="prev">Left</span>
    </div>
  </div>

  <div class="words-loading-img"><img src="/images/show/slider/waiting.gif" /></div>

</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/_tags_list.html.erb
<div id="tag-box" class="tags">
  <div id="tags-box-header">All the tags of yourself:</div>
  <div id="tags-list">
	
	<% @user_tags = Array.new %>
	<% @user.word.each do | word | %>
    <%   word.tags.each do | tag |%>
    <%	    @user_tags.push(tag) %>
	<%   end  %>
	<% end %>
	
	<ul> 
    <% @user_tags.uniq! %>
	<% if @user_tags.length > 0 %>
	<%   @user_tags.sort! do |tag_a, tag_b| %>
	<%     tag_b.updated_at <=> tag_a.updated_at %>
	<%   end %>	 
    
    <%   @user_tags.each do | tag | %>	
    <li>
	       <%= link_to tag.name, show_tag_word_path(:id => @user.id, :name => "#{tag.name}")  %>
	</li>
	<%   end %>
    
    </ul>

    <% else %>
          <div id='no-tag-message'>There is no tag</div>
	<% end %>
    
    <div id = 'tag-all-link'>
       <%= link_to 'All words', show_tag_word_path(:id => @user.id, :name => "all") %>
	</div>
	
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
<head>
  <title>
    <%= @title %>
  </title>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'reset', :media => 'screen' %>
  <%= stylesheet_link_tag 'keepin', :media => 'screen' %>
  <%= stylesheet_link_tag 'flip', :media => 'screen' %>
  <%= stylesheet_link_tag 'word', :media => 'screen' %>
  <%= stylesheet_link_tag 'show', :media => 'screen' %>
  <%= stylesheet_link_tag 'show_slider', :media => 'screen' %>
  <%= stylesheet_link_tag 'pagination', :media => 'screen' %>
  <%= stylesheet_link_tag 'jquery-ui-1.8.14.custom', :media => 'screen' %>
  <%= stylesheet_link_tag 'addon', :media => 'screen' %>
  <%= javascript_include_tag 'jquery-1.4.4' %>
  <%= javascript_include_tag 'jquery.flip' %>
  <%= javascript_include_tag 'jquery-ui-1.8.14.custom.min' %>
  <%= javascript_include_tag 'slides.min.jquery' %>
  <%= javascript_include_tag 'pagination' %>
  <%= javascript_include_tag 'words.lister' %>
</head>
<body class="home">
<%= render 'layouts/header' %>
<div id="wrapper">
  <div id="main">
    <%= yield %>
  </div>
</div>
</body>
</html>